name: Docker Image Build and Push - CI Workflow

on:
  push:
    branches:
      - 'v*'
    
    tags:
      - 'v*'

jobs:
  build-and-push-muti-arch-docker-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bluven/net-tool
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Docker Image Tags
        id: prep
        run: |
          TAGS="${IMAGE_NAME}:latest,${IMAGE_NAME}:${GITHUB_REF_NAME}"
          echo "Complete Docker image-name and tags are setup as: ${TAGS}"
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
